format="${custom.ssh}${custom.yazi}${custom.nnn}$all"

[username]
show_always = true
format = "[$user]($style)@"

[hostname]
ssh_only = false
trim_at = ""
style = "bold green"
format = "[$hostname]($style) "

[directory]
truncate_to_repo=false
style='bold blue'

[git_branch]
format = "on [$branch]($style) "

[package]
format = "[$symbol$version]($style) "

[cmd_duration]
disabled = true

[custom.ssh]
when = "test $SSH_CLIENT"
format = "[ssh](purple bold) "

[custom.nnn]
when = "test $NNNLVL"
format = "[nnn](purple bold) "

[custom.yazi]
description = "Indicate the shell was launched by `yazi`"
symbol = "îž• "
# symbol = "yazi(purple bold) "
when = """ test -n "$YAZI_LEVEL" """

[gcloud]
disabled = true

[shell]
disabled = false
style = "blue"

[nix_shell]
heuristic = true
